apiVersion: v1
kind: Service
metadata:
  name: file-logger-service
spec:
  selector:
    app: file-logger
  type: NodePort
  ports:
  - protocol: TCP
    port: 8788
    targetPort: 8788
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-logger
  template:
    metadata:
      labels:
        app: file-logger
    spec:
      restartPolicy: Always
      containers:
      - image: docker.io/alexmerenstein/f3-file-logger:0.0.2
        #command: ["/server", "-listen-port", "8788", "-save-file", "/log/save-file"]
        command: ["tail", "-f", "/dev/null"]
        name: test
        ports:
        - containerPort: 8788
        volumeMounts:
        - mountPath: /log
          name: log
      volumes:
      - name: log
        hostPath:
          path: /var/log/f3/file-logger
          type: DirectoryOrCreate
