---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: f3
provisioner: f3.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  server: "/mnt/local-cache/tempdir/"
